name: 'Release version of the Github action'

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Set the proper version name to be used `v1` etc.'
        required: true

jobs:
  start-release:
    runs-on: ubuntu-latest
    steps:
      - name: Update the release notes.
        uses: appsfortableau/github-action-releaser@v1
        with:
          tag_name: '${{ inputs.VERSION }}'
          move_tag: true
